# Generated by Django 5.1.6 on 2025-03-19 18:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='auction',
            old_name='winner',
            new_name='winner_id',
        ),
    ]
