# Generated by Django 5.1.6 on 2025-03-19 19:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_rename_winner_auction_winner_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='auction',
            old_name='winner_id',
            new_name='current',
        ),
    ]
