# Generated by Django 5.1.6 on 2025-03-19 19:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_rename_winner_id_auction_current'),
    ]

    operations = [
        migrations.CreateModel(
            name='Winners',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Winner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='won', to=settings.AUTH_USER_MODEL)),
                ('auctions', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='winners', to='auctions.auction')),
            ],
        ),
    ]
