# Generated by Django 5.1.6 on 2025-03-19 19:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_winners'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='won_auctions',
            field=models.ManyToManyField(blank=True, related_name='Won_auctions', to='auctions.auction'),
        ),
        migrations.AlterField(
            model_name='auction',
            name='current',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='current_winner', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Winners',
        ),
    ]
