# Generated by Django 5.1.6 on 2025-03-23 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0006_alter_auction_category'),
    ]

    operations = [
    ]
